### ISSUE TITLE
Not Found 后返回浏览器标题不会改变

### ISSUE THREAD

**Issue by WrunDorry** [Starlight-Dev-Team/fanbook-bot-tools#78]
Not Found 后返回到 `index` 浏览器标题不会改变
![image](https://fanbookwdg3.bailituya.com/i/2023/05/23/x6m3i5.png)

**Comment by kaikaibenkai** [comment]
这个是 Nuxt 的问题，我试试绕开一下

**Comment by kaikaibenkai** [comment]
[bug] 直接进入 404 需要按两次返回才能返回
