### ISSUE TITLE
二次all users卡在获取成员列表里

### ISSUE THREAD

**Issue by WrunDorry** [Starlight-Dev-Team/fanbook-bot-tools#83]
在同一页面下，第一次all users私信通知成员完毕后，再次all users私信通知成员总是会卡在获取成员列表里。
![img](https://fb-cdn.fanbook.mobi/fanbook/app/files/chatroom/image/c6719cb618242956870c3fb793c1746f.png)

**Comment by kaikaibenkai** [comment]
这个 bug 预计在重构发消息功能后测试解决

**Comment by kaikaibenkai** [comment]
fixed by #88
