### ISSUE TITLE
草稿功能一直在加载，似乎无法正常使用

### ISSUE THREAD

**Issue by wangdage12** [Starlight-Dev-Team/fanbook-bot-tools#94]
![屏幕截图 2023-06-18 134845](https://github.com/Starlight-Dev-Team/fanbook-bot-tools/assets/124357765/c04bf258-ee20-4532-81d9-8ce36e6faae1)

**Comment by kaikaibenkai** [comment]
麻烦提供一下浏览器 User Agent，初步看应该是 IndexedDB 的问题

**Comment by wangdage12** [comment]
![image](https://github.com/Starlight-Dev-Team/fanbook-bot-tools/assets/124357765/06c6732e-cfa4-4aa7-835c-0e59fee8273e)
